<h3>UROCZYSTOŚĆ WNIEBOWSTĄPIENIA PAŃSKIEGO - 29.05.2022 R. </h3>

<p>
<ol>
<li><p>Przeżywamy Uroczystość Wniebowstąpienia Pańskiego.</p></li>
<li><p>Nabożeństwo majowe w kościele parafialnym dzisiaj, poniedziałek i wtorek o godz. 17:30, a od godz. 17:00 Adoracja Najświętszego Sakramentu. Zachęcamy do uczestnictwa w tej modlitwie. &nbsp;Od środy 1 czerwca codziennie od godz. 17:00 Adoracja Najświętszego Sakramentu, a o godz. 17:45 litania do Serca Pana Jezusa i Msza Święta.</p></li>
<li><p>Składamy serdeczne podziękowanie za złożone dzisiaj ofiary na tacę. Bóg zapłać. &nbsp;</p></li>
<li><p>W tym tygodniu będziemy przeżywać następujące wspomnienia i wydarzenia liturgiczne.&nbsp;</p><p><strong>a) Wtorek&nbsp;</strong>– Święto Nawiedzenia Najświętszej Maryi Panny. &nbsp;&nbsp;</p><p><strong>b) Środa</strong> – wspomnienie św. Justyna, męczennika. &nbsp;Przed Mszą Świętą wieczorną nowenna do Matki Bożej Nieustającej Pomocy.&nbsp;</p><p><strong>c) Czwartek&nbsp;</strong>– przed Mszą Świętą wieczorną nabożeństwo do św. Jana Pawła II w intencji małżonków, dzieci i młodzieży. Osoby, które chcemy polecać w modlitwie Panu Bogu przez wstawiennictwo św. Jana Pawła II należy wypisać na przygotowanych karteczkach, które znajdują się na bocznych ołtarzach i pod chórem i złożyć przed nabożeństwem do koszyczka. Na wieczorną Mszę Świętą zapraszamy uczniów klas siódmych przygotowujących się do egzaminu i sakramentu bierzmowania. Zachęcamy młodzież do spowiedzi świętej. Na spotkanie zapraszamy również rodziców.&nbsp;</p><p><strong>d) Piątek</strong> – wspomnienie św. Karola Lwangi i Towarzyszy, męczenników. Z racji pierwszego piątku miesiąca o godz. 15:00 godzina miłosierdzia i okazja do spowiedzi świętej. W tym dniu naszymi ofiarami wspieramy prowadzone przez misjonarzy dzieła misyjne. Tradycyjnie udamy się również z posługą sakramentalną do chorych.&nbsp;</p><p><strong>e) Sobota&nbsp;</strong>– po Mszy Świętej o godz. 6:30 nabożeństwo wynagradzające Niepokalanemu Sercu Maryi. Nabożeństwo pierwszo sobotnie w Czaczowie i Frycowej o godz. 8:00.&nbsp;</p><p><strong>f) Niedziela </strong>– Uroczystość Zesłania Ducha Świętego.&nbsp;</p></li>
<li><p>Zachęcamy do lektury prasy katolickiej; jest do nabycia nowy numer Gościa Niedzielnego, tygodnik Niedziela, Idziemy, a także Mały Gość Niedzielny.</p></li>
<li><p>Składamy serdeczne podziękowanie rodzicom dzieci, które w tym roku przystąpiły do sakramentu pierwszej spowiedzi i komunii świętej za złożoną ofiarę na dar ołtarza, a także za wszelką pomoc w zorganizowaniu tego ważnego dla dzieci dnia. Bóg zapłać.&nbsp;</p></li>
<li><p>Spowiedź święta w tym tygodniu.</p><p><strong>a) Kościół parafialny</strong></p><ul><li>codziennie pół godz. przed Mszą Świętą&nbsp;</li><li>środa – czwartek od godz. 17:00</li><li>piątek – od godz. 15:00</li></ul><p><strong>b) Kaplice dojazdowe</strong></p><ul><li>Czaczów – Środa od godz. 18:00</li><li>Frycowa – Czwartek od godz. 18:00</li><li>Złotne – Piątek od godz. 18:00</li><li>Bącza – Piątek od godz. 6:30</li></ul></li>
<li><p>W minionym tygodniu do wieczności odeszła śp. Anna Krzesz z Bączej Kuniny oraz śp. Krzysztof Waligóra z Nawojowej, którego pogrzeb odbędzie się w poniedziałek 30 maja o godz. 12:30 różaniec i Msza Święta w kaplicy cmentarnej. Polećmy ich nieśmiertelne dusze miłosierdziu bożemu.</p></li>
</ol>
</p>

<div id='ogloszenia-nadeslane'>
<h3 style='background-color:#ffc000;'>OGŁOSZENIA NADESŁANE</h3>
<div class='content-new-ogloszenia'>
<ol><li>Wójt Gminy Nawojowa przypomina o obowiązku złożenia deklaracji dotyczącej źródeł ciepła i spalania paliw w budynkach mieszkalnych i niemieszkalnych. Ogłoszenie dotyczy mieszkańców, którzy jeszcze nie złożyli deklaracji. Termin składania deklaracji do 30 czerwca 2022r. W przypadku pytań, prosimy o kontakt z urzędem.</li><li>Gminny Ośrodek Kultury w Nawojowej zaprasza w przyszłą niedzielę 05 czerwca br. Na Zielone Świątki w Nawojowej. Początek o godzinie 15:00 na estradzie plenerowej&nbsp; ul. Lipowa 3 /stadion sportowy/, w programie m.in. występy zespołów regionalnych, kiermasze, wystawy i degustację. Szczegóły na afiszach i stronie internetowej gok. Organizatorzy serdecznie zapraszają.</li></ol><br>
</div>
</div>